### ISSUE TITLE
List of supported versions in the Plugins directory

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-quiz_export#1]
The currently uploaded version https://moodle.org/plugins/pluginversion.php?id=23433 has only "Moodle 2.7" selected as supported version.

I suppose the intention was to mark all versions **since** 2.7 as supported?

Please note, the plugins directory requires that all supported versions are explicitly selected. Please edit the version record and mark all supported Moodle versions.

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Supported_Moodle_versions

**Comment by MallauryGerard** [comment]
Done !
Thanks ! That was a mistake.

**Comment by mudrd8mz** [comment]
Yeah. It's on our TODO list to improve the plugins directory UI and also make it more smart about this. Thank you.
