### ISSUE TITLE
Fatal error when running

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-quiz_export#2]
Fatal error: require_once(): Failed opening required '.../mod/quiz/report/export/vendor/autoload.php' in .../mod/quiz/report/export/export.php on line 14

**Comment by MallauryGerard** [comment]
> Fatal error: require_once(): Failed opening required '.../mod/quiz/report/export/vendor/autoload.php' in .../mod/quiz/report/export/export.php on line 14

Hello,
Thank you for your feedback.
The plugin requires a package (mpdf) to be installed. I just saw that Moodle does not recommend to install it from "composer install".
So which method do you recommend? Should I include the vendor directory into the zip file?

Regards,

Mallaury

**Comment by mudrd8mz** [comment]
> Should I include the vendor directory into the zip file?

Yeah. All Moodle plugins must do it like that. The reasoning behind is that many admins do not have access to their server shell and/or are not experienced with PHP building tools. So Moodle plugins are supposed to be distributed in packages that work out of the box.

Please double check the licence compatibility to make sure that you can distribute 3rd party libraries with your plugin's GPLv3 code. See https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing for details.

Finally, it is best to avoid additional dependencies if possible. Moodle core already ships with `tcpdf` library and it would be easiest to just re-use it (not requirement, just recommendation).

TIA

**Comment by MallauryGerard** [comment]
I did that. Thank for your advices.
