### ISSUE TITLE
PHP notices when attempting to export, leading to broken output stream

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-quiz_export#3]
Notice: tempnam(): file created in the system's temporary directory in /home/mudrd8mz/www/mdk/m310/moodle/mod/quiz/report/export/export.php on line 55

Notice: tempnam(): file created in the system's temporary directory in /home/mudrd8mz/www/mdk/m310/moodle/mod/quiz/report/export/export.php on line 59

Warning: Cannot modify header information - headers already sent by (output started at /home/mudrd8mz/www/mdk/m310/moodle/mod/quiz/report/export/export.php:55) in /home/mudrd8mz/www/mdk/m310/moodle/mod/quiz/report/export/report.php on line 189

Warning: Cannot modify header information - headers already sent by (output started at /home/mudrd8mz/www/mdk/m310/moodle/mod/quiz/report/export/export.php:55) in /home/mudrd8mz/www/mdk/m310/moodle/mod/quiz/report/export/report.php on line 190

![image](https://user-images.githubusercontent.com/85831/110695862-aaa1e880-81ea-11eb-96d9-7dbdcfbeac62.png)

**Comment by MallauryGerard** [comment]
Hello @mudrd8mz 

Thanks for your feedback, I just realised that the plugin is actually only compatible up to 3.8.
I will look for a solution with my colleagues. 

Thanks
