### ISSUE TITLE
Vendor class is missing again

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-quiz_export#4]
The latest version 2.2.0 (Build 2021110200) https://moodle.org/plugins/pluginversion.php?id=23753 does not have the "vendor" folder again.

Same issue as the one discussed in issue #2 

Please refer to:

* https://docs.moodle.org/dev/Plugin_contribution_checklist#Dependencies
* https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing

**Comment by binote00** [comment]
New version released (3.9.0) with vendor folder in the zip
