### ISSUE TITLE
Confusing version numbers

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-quiz_export#5]
It is confusing to have two versions called "2.2.0 (Build 2021110200)" is not it?

![image](https://user-images.githubusercontent.com/85831/112311798-614f9f80-8ca6-11eb-89a6-cd3306b0d273.png)

**Comment by binote00** [comment]
New version released (3.9.0)

Bad version hided because i can't delete it.

**Comment by mudrd8mz** [comment]
OK. I deleted it.
