### ISSUE TITLE
Third party libs cause zillions coding style errors reported

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-quiz_export#6]
There are thousands and thousands coding style violations reported:

![image](https://user-images.githubusercontent.com/85831/112870084-1e366780-90be-11eb-97ad-fb53ffc5550d.png)

I believe many could be avoided if more attention was paid to https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing and https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml 

This would not only make a solid declaration of GPLv3 compliance but also lead to much more reliable results of the prechecker.

**Comment by binote00** [comment]
New version submitted

Tag 3.9.0.1
