### ISSUE TITLE
Cloze question format

### ISSUE THREAD

**Issue by RevanJS** [cbluesprl/moodle-quiz_export#7]
Hello,

really great plugin! I'm having an issue with exporting cloze questions. There seems to be a formatting issue since the entered answer won't be displayed in correspondence with the right answer.  
An example is shown in the image.

![formatting](https://user-images.githubusercontent.com/84582701/119159841-f4634680-ba57-11eb-83da-affcf8da7686.PNG)

best regards

**Comment by renaudlemaire** [comment]
Hello RevanJS,

The given answer will be now displayed.
Unfortunatly, the "incorrect box" displayed right after the given answer in the original html code (showed by mouse over) and cant be easily moved in our pdf version.

Best Regards,

Renaud.

**Comment by RevanJS** [comment]
Thank you very much!
