### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by englishwebtls** [cbluesprl/moodle-quiz_export#8]
Hello 
I get this error when trying to update to latest version:
Debugging output enabled
Validating quiz_export ... Error
  [Error] Extracted file not found [{"file":"export\/vendor\/mpdf\/mpdf\/tmp\/"}] 
Installation aborted due to validation failure
Moodle 3.11

**Comment by yllxlxj** [comment]
When exporting to Chinese, the characters cannot be displayed normally because of garbled characters. How can I solve the problem?
[_计算机2001 姬文帆.pdf](https://github.com/cbluesprl/moodle-quiz_export/files/8694182/_.2001.pdf)
?

**Comment by tholudwig** [comment]
Hi,

for me following the [instructions ](https://github.com/cbluesprl/moodle-quiz_export#installation) did the job.
Installing it locally brings up an Moodle-Error. You can either fix it by using `composer install  --ignore-platform-reqs` (for local try) or by adding the extionsion to your php.ini.

**Comment by shenrard** [comment]
Hello, 

I am closing this ticket because the vendor is now included directly in the repository.
